# Introducción
El pass-through cambiario se define conceptualmente como la variación porcentual en los precios internos (por ejemplo, el índice de precios al consumidor o a los precios de importación) resultante de un cambio del uno por ciento en el tipo de cambio entre países exportadores e importadores [@Goldberg1997]. Este fenómeno es crucial para el debate sobre políticas monetarias apropiadas y estabilidad macroeconómica. En un escenario de una economía pequeña y abierta, como el caso de Guatemala, el tipo de cambio es un canal de transmisión de choques económicos que afecta la estructura de costos interna de las empresas y, en consecuencia, a los precios del consumidor final [@Orenos]. Dada la adopción del esquema de metas explícitas de inflación en Guatemala desde 2005, cuyo objetivo primordial es mantener la estabilidad del nivel general de precios, resulta fundamental para la autoridad monetaria comprender la magnitud (coeficiente de traspaso) y la velocidad con que los movimientos cambiarios se trasladan a los precios internos.

La pregunta central de esta investigación es: ¿cuál es la magnitud y velocidad del pass-through cambiario del tipo de cambio nominal hacia la inflación en Guatemala, de acuerdo con la evidencia de un modelo VAR? El análisis de esta pregunta, tal y como lo comentan los autores @Choudhri2006, se enmarca en la teoría que sugiere una relación positiva y significativa entre el entorno inflacionario y la magnitud del pass-through. La literatura muestra que un entorno de baja inflación está asociado con una menor persistencia esperada de los choques de costos y precios, lo que reduce el incentivo de las empresas para ajustar sus precios, lo cual resulta en un menor pass-through. El papel de la credibilidad del Banco Central (Banguat) en el anclaje de las expectativas y la reducción de la persistencia esperada es un elemento teórico clave para interpretar el caso guatemalteco, donde el uso de la tasa de interés líder de la política monetaria busca influir en la meta de inflación bajo el esquema de metas explícitas de inflación.

Para capturar las relaciones dinámicas y posiblemente bidireccionales entre el tipo de cambio y los precios internos, se emplea la metodología de un modelo de vectores autorregresivos (VAR), ya que una regresión de pass-through de una sola ecuación no considera que la inflación doméstica pueda afectar al tipo de cambio [@Ito2008]. Este enfoque multivariado es necesario para el estudio empírico del pass-through, permitiendo examinar el mecanismo de transmisión a través de las funciones impulso-respuesta (mediante una identificación de choques estructurales), lo que permite medir los impactos en el nivel de precios a lo largo de un horizonte temporal. La contribución principal de este estudio es proveer evidencia empírica sobre la magnitud y velocidad del pass-through en Guatemala, contextualizando sobre el régimen de metas explícitas de inflación para amortiguar los choques cambiarios, lo cual es parte fundamental para la evaluación y conducción de la política monetaria.

El presente trabajo se estructura en cinco secciones. La sección 2 presenta la revisión de literatura relevante sobre los determinantes del pass-through y la conceptualización del mismo. La sección 3 describe los datos y la metodología econométrica empleada, detallando la especificación del modelo VAR. Posteriormente, la sección 4 muestra los resultados empíricos y su discusión. Finalmente, la sección 5 presenta las conclusiones derivadas de los resultados obtenidos y, algunas implicaciones de política económica.

