# Revisión de la literatura

## Pass-through del tipo de cambio y precios internos

Conceptualmente, @Goldberg1997 definen pass-through como la variación porcentual en los precios de importación denominados en moneda nacional (o doméstica) resultante de un cambio del uno por ciento en el tipo de cambio entre países exportadores e importadores. Por su parte, @Orenos lo conceptualiza como el efecto de la depreciación nominal del tipo de cambio sobre el nivel general de precios internos de una economía.

@Orenos retoma la distinción entre los dos canales mediante los cuales el efecto de pass-through se transmite a los precios internos; estos son el canal directo y el indirecto. El efecto directo o de primer orden se manifiesta de manera secuencial: un choque cambiario modifica inicialmente el precio de los bienes importados (de consumo, insumos o capital), que luego se traslada a la estructura de costos interna de las empresas y, en última instancia, al consumidor final. Por otra parte, el canal indirecto opera a través de la demanda agregada; una depreciación cambiaria abarata los bienes domésticos, aumentando su demanda y generando una presión al alza sobre los precios internos.

El análisis de pass-through se centra en tres características fundamentales: la magnitud (coeficiente de traspaso) y la simetría (si la respuesta es la misma a la apreciación y a la depreciación).

## Política monetaria, expectativas y actividad económica
	
El grado de pass-through (la magnitud), no depende únicamente de factores microeconómicos, sino también de elementos macroeconómicos, siendo el entorno inflacionario un determinante clave.

### El papel de la política monetaria y las expectativas

@Taylor2000 argumenta que el grado de pass-through depende de la persistencia esperada de los choques de costos o precios, siendo una baja inflación asociada con una menor persistencia de la inflación y de los cambios en los costos (como los cambiarios). Por lo tanto, si un choque cambiario es percibido como temporal (baja persistencia), las empresas tienen menos incentivos para ajustar sus precios (por el objetivo de mantener la cuota de mercado), resultando en un menor pass-through. Este entorno de baja inflación, promovido por una política monetaria con credibilidad, actúa como un amortiguador ante choques adversos a los precios. 

En contraste, en escenarios de alta inflación, existe mayor incertidumbre y las empresas tienden a cambiar sus precios con mayor frecuencia, por lo que el traspaso es mayor. @Orenos, sugiere ante la evidencia empírica que la disminución del pass-through en regímenes de baja inflación se debe a un debilitamiento de la covarianza entre el tipo de cambio y los precios.

Bajo lo mencionado sobre los resultados de @Taylor2000, se muestra que el papel de la política monetaria es fundamental para la credibilidad y el anclaje de expectativas. Por lo que, si se generalizan las ideas anteriores: en un entorno de baja incertidumbre, cuando el Banco Central ha logrado consolidar una postura monetaria coherente con la meta de inflación, los agentes económicos confiarán en que la autoridad actuará para mantener dicha meta, haciendo que las expectativas no se desvinculen y que el pass-through sea pequeño.

Otros autores como @Choudhri2006, utilizando una muestra amplia de países, encontraron una asociación positiva y significativa entre el pass-through y la tasa de inflación promedio. Es decir, el pass-through a los precios internos tiende a ser mayor en países con experiencias inflacionarias más altas.

@Campa2005 también proporcionaron evidencia con respecto al tema, sugiriendo que la volatilidad cambiaria y la volatilidad inflacionaria de un país se correlacionan positivamente con el pass-through a los precios de importación, encontrando también que la estabilidad monetaria hace que la política monetaria sea más efectiva al reducir el pass-through.

### El papel de la actividad económica

El ciclo económico influye en la capacidad de las empresas para trasladar los choques de costos a los precios [@Orenos]. El pass-through es mayor en periodos de expansión económica (aumento de la demanda) ya que las empresas tienen mayor facilidad para trasladar los choques a los precios. Por el contrario, en escenarios de recesión (caída de la demanda), la capacidad de trasladar los choques disminuye [@Goldfajn2000]. De esta manera, la fase del ciclo económico puede condicionar el grado del pass-through. 

## Marco econométrico: VAR/SVAR

Para el estudio empírico del pass-through es necesario el uso de un marco que permita capturar las relaciones dinámicas y bidireccionales entre las variables macroeconómicas. 

Una regresión de pass-through de una sola ecuación ignora que la inflación doméstica puede afectar al tipo de cambio, lo cual hace necesario un modelo VAR con el fin de examinar un mecanismo entre los precios internos y el tipo de cambio [@Ito2008].

@McCarthy2007 utiliza un modelo VAR recursivo con descomposición de Cholesky para identificar choques estructurales (SVAR), permitiendo medir los impactos en el nivel de precios a lo largo de un horizonte temporal mediante las funciones de impulso-respuesta; y con base en los estudios de @Ito2008, se conoce que las variables típicas incluidas en estos modelos son el tipo de cambio, índices de precios, la inflación, nivel de actividad económica y variables de política monetaria.

## Particularidades del caso guatemalteco

La literatura que proporcionan autores como @Taylor2000, @Choudhri2006, @Campa2005, entre otros, es crucial porque establece la credibilidad del Banco Central y el anclaje de las expectativas como el principal mecanismo detrás de la reducción del pass-through. Estos resultados sirven como referencia para interpretar el caso guatemalteco.

### Régimen monetario y estabilidad: esquema de metas explícitas de inflación

Formalmente, Guatemala implementó el esquema de metas explícitas de inflación en 2005, en el cual el objetivo principal de la autoridad monetaria es mantener la estabilidad del nivel general de precios, utilizando como instrumento operativo la tasa de interés líder de política monetaria (TILPM). En este marco, la TILPM actúa como tasa de referencia de muy corto plazo, a partir de la cual se busca influir sobre el resto de tasas de interés del sistema financiero, las expectativas de inflación y otras variables macroeconómicas relevantes, como el producto y el tipo de cambio.

La Junta Monetaria tenía la motivación de reflejar la importancia de asegurar condiciones que favorezcan la estabilidad macroeconómica, mediante la adopción de una orientación de política económica que en los campos fiscal y comercial pueda respaldar y complementar un proceso sostenido de reducción de la inflación que viabilice su convergencia hacia niveles inflacionarios similares a los prevalecientes en países de mayor desarrollo que permita la competitividad del país [@JuntaMonetaria2005].

El diseño del esquema de metas de inflación en Guatemala ha sido acompañado de estudios sobre su marco teórico y su efectividad, que resaltan la importancia de comprender el mecanismo de transmisión de la política monetaria para evaluar la pertinencia de las decisiones de tasa de interés.

Con respecto al tipo de cambio, Guatemala liberalizó el mercado cambiario en 1989. La política cambiaria actual (desde 2011) se enfoca únicamente en moderar la volatilidad del tipo de cambio mediante reglas de participación en el mercado, asegurando que no se afecte la tendencia de largo plazo [@JuntaMonetaria2011].

En general, la regla de participación consiste en la vigilancia de los promedios ponderados, donde se establece un  margen inferior para operaciones de compra y uno de margen superior para las de venta. Si el tipo de cambio promedio ponderado se encuentra por fuera de dichos límites, el Banco de Guatemala activa la regla de participación.

