# Metodología de investigación

En este estudio se utilizaron datos tomados del Banco de Guatemala y de la Secretaría Ejecutiva del Consejo Monetario Centroamericano, que abarcaron el periodo que inicia en enero 2001 y termina en septiembre 2025.

## Variables y datos
Para realizar la modelación del fenómeno fue necesario construir variables que fuesen estacionarias dado que los datos brutos no poseen esta propiedad. Dicha construcción se realizó a partir de las variables crudas que se muestran en la tabla \ref{tab:variables}.

```{=latex}
\begin{table*}
\centering
\caption{Variable, cantidad, frecuencia y origen de datos}
\label{tab:variables}
\begin{tabular}{lccc}
\toprule
\textbf{Variable} & \textbf{Numero de datos} & \textbf{Periodicidad} & \textbf{Fuente} \\
\midrule
Índice de precios al consumidor (IPC) & 297 & mensual & Banco de Guatemala \\
Tipo de cambio nominal (TCN) & 297 & mensual & Banco de Guatemala \\
Tipo de cambio efectivo real (ITCER) & 297 & mensual & SECMCA \\
Índice mensual de la actividad económica (IMAE) & 297 & mensual & Banco de Guatemala \\
\bottomrule
\end{tabular}
\caption*{Fuente: elaboración propia}
\end{table*}
```

A continuación se detallan las transformaciones realizadas a estas variables y los valores resultantes, metodología que fue tomada de @CarpioSam2007, y las cuales fueron empleadas en el modelo VAR.

### Inflación mensual anualizada

Con el fin de suavizar el comportamiento de la inflación, se calculó la inflación mensual anualizada como se muestra en la ecuación \ref{ec:inf-men-an}.

\begin{equation} \label{ec:inf-men-an}
\Delta \pi_{t} = \left( 1 + \varphi_t \right)^{12} - 1
\end{equation}
donde:
$$
\varphi_t = \frac{IPC_t - IPC_{t-1}}{IPC_{t-1}}
$$

Esta expresión representa el valor de la inflación si en 12 meses consecutivos ésta hubiese sido constante.

### Variación mensual anualizada del tipo de cambio nominal

Para esta variable también fue necesario suavizar su comportamiento, por lo que se empleó la ecuación \ref{ec:tcn-men-an} para lograr este objetivo.

\begin{equation} \label{ec:tcn-men-an}
\Delta tc_{t} = \left( 1 + \Delta e_t \right)^{12} - 1
\end{equation}

donde:
$$
\Delta e_t = \frac{TCN_t - TCN_{t-1}}{TCN_{t-1}}
$$

Esta expresión representa el valor de la variación del tipo de cambio nominal si en 12 meses consecutivos ésta hubiese sido constante.

### Desalineación del tipo de cambio efectivo real

La desalineación del tipo de cambio efectivo real representa el desvío de esta variable respecto de su tendencia. La tendencia se obtuvo aplicando el filtro Hodrick-Prescott con parámetro $\lambda = 14,\, 400$. Esta desalineación se calculó mediante la ecuación \ref{ec:tcr-gap}:

\begin{equation} \label{ec:tcr-gap}
tcr_{gap,t} = \frac{ITCER_t - ITCER_{hp,t}}{ITCER_{hp,t}}
\end{equation}

### Brecha del producto
Debido a que el Producto Interno Bruto (PIB) no se mide con la frecuencia necesaria, se emplea el IMAE como proxy del PIB, ya que este índice mide el volumen de producción en un mes. Adicionalmente se desea saber que tanto por encima o por debajo del PIB potencial se encuentra la economía de Guatemala. Para estimar este PIB potencial, de nuevo se aplica el filtro Hodrick-Prescott al IMAE y se extrae su tendencia. La brecha fue calculada mediante la ecuación \ref{ec:y-gap}:

\begin{equation} \label{ec:y-gap}
imae_{gap,t} = \frac{IMAE_t - IMAE_{hp,t}}{IMAE_{hp,t}}
\end{equation}


## Modelo
Para poder evaluar el efecto passthrough del tipo de cambio en la economía de Guatemala se utilizó un modelo VAR con variables dicotómicas de estacionalidad (o variables dummy) y restricciones de corto plazo recursivas (Cholesky), descrito por @Sims1980. El objetivo de esta última es imponer un orden sobre como responden las variables, empezando por la más exógena y terminando con la más endógena. 

Siguiendo la notación de @Enders, un modelo VAR(p) estructural con variables dummy está dado por:

\begin{equation}\label{ec:varp_e}
B X_t = \Gamma_0 + \sum_{j=1}^{p} \Gamma_j X_{t-j} + \Phi S_t + \varepsilon_t, \; t = 1,\ldots, T
\end{equation}

donde $X_t$ es un vector $4 \times 1$ que contiene a las variables $tcr_{gap,t}$, $imae_{gap,t}$, $\Delta tc_{12}$ y $\Delta \pi_{t}$; $\Gamma_p$ son matrices de coeficientes de dimension $4 \times 4$, $\Phi$ es la matriz de coeficientes de las variables dummy estacionarias de dimensión $4 \times 11$, $S_t$ es el vector que contiene a las variables dummy $\left( D_{Ene,t}, \ldots, D_{Nov,t} \right)^T$ (sin la dummy para diciembre para evitar multicolinealidad, por lo que diciembre funciona como el mes base) y $\varepsilon_t$ es un vector $4 \times 1$ de error de predicción con una matriz de covarianza $\mathbb{E}\left[ \varepsilon_t \varepsilon_t^T \right] = I_4$, también llamado vector de choques estructurales.

Sin embargo, como el modelo estructural no puede ser estimado directamente, se recurre a su forma reducida, la cual podemos expresar como:

\begin{equation}\label{ec:varp_r}
X_t = A_0 + \sum_{j=1}^{p} A_j X_{t-j} + \Psi S_t + e_t, \; t = 1,\ldots, T
\end{equation}

donde $A_0 = B^{-1} \Gamma_0$, $A_p = B^{-1} \Gamma_p$, $\Psi = B^{-1} \Phi$ y $e_t = B^{-1} \varepsilon_t$ y su matriz de covarianza es $\mathbb{E}\left[ e_t e_t^T \right] = \Sigma_e$.

Donde el número óptimo de rezagos ($p$) se determinó utilizando el criterio de información de Akaike, dado que, para realizar pronósticos, es el criterio que devuele el mejor modelo.

Como el modelo reducido estima 6 parámetros menos que el modelo estructural, se imponen sobre este último 6 restricciones para poder identificarlo a partir de la estimación realizada para el modelo reducido. El esquema de identificación se detalla en la siguiente sección.


## Esquema de identificación

Tal como lo expresa @Sims1980, para poder identificar el modelo estructural a partir del modelo reducido, se triangulariza la matriz $\Sigma_e$, lo cual implica que impone un orden en la que las variables reaccionan a las innovaciones.

A la triangularización descrita por Sims, se le conoce como la descomposición de Cholesky. Para realizar esta descomposición partimos de su definición

\begin{equation}
\Sigma_e = \mathbb{E}\left[ e_t e_t^T \right] 
\end{equation}

Si $e_t = P \varepsilon_t$, entonces tenemos

\begin{align}
\Sigma_e &= \mathbb{E} \left[ e_t e_t^T \right] \\
 &= \mathbb{E} \left[ \left( P \varepsilon_t \right) \left( P \varepsilon_t \right)^T \right] \\
 &= P \, \mathbb{E} \left[ \varepsilon_t \varepsilon_t^T \right] \, P^T
\end{align}

Como asumimos que el vector de choques estructurales no están correlacionados $\left( \mathbb{E}\left[ \varepsilon_t \varepsilon_t^T \right] = I_4 \right)$, entonces lo anterior se puede simplificar a.

\begin{equation} \label{ec:covsigma}
\Sigma_e = P P^T
\end{equation}

Como existen varias matrices $P$ que pueden satisfacer la ecuación \ref{ec:covsigma}, entonces se aprovecha su simetría para imponer una restricción específica: $P$ debe ser una matriz triangular inferior. Esto quiere decir que todos los valores por encima de la diagonal principal deben ser cero. Esto es:

$$
P = 
\begin{pmatrix}
p_{11} & 0 & 0 & 0 \\
p_{21} & p_{22} & 0 & 0 \\
p_{31} & p_{32} & p_{33} & 0 \\
p_{41} & p_{42} & p_{43} & p_{44}
\end{pmatrix}
$$

Lo cual nos lleva a las siguientes soluciones: para los elementos sobre la diagonal principal tenemos

\begin{equation}
p_{ii} = \sqrt{\sigma_i^2 -\sum_{k=1}^{i-1} p_{ik}^2}
\end{equation}

y para las soluciones afuera de ésta tenemos

\begin{equation}
p_{ij} = \frac{\sigma_{ij} -\sum_{k=1}^{j-1} p_{ik} p_{jk}}{p_{jj}}, \; \text{para} \; i > j
\end{equation}

Para recuperar $\Gamma_0$, $\Gamma_p$ y $\Phi$ observamos que 
$$
P = B^{-1}
$$

Por lo que $\Gamma_0 = P^{-1} A_0$, $\Gamma_p = P^{-1} A_p$ y $\Phi = P^{-1} \Psi$

Como la forma de ordenar las variables importa, ordenan las variables de tal forma que la variable que tome más tiempo en reaccionar es la primera (y por ello las más exógena) y la que tome menos tiempo en reaccionar es la última (y por ello la más endógena). En este trabajo, se ordenó las variables de la siguiente forma: $tcr_{gap,t}$, $imae_{gap,t}$, $\Delta tc_t$ y $\Delta \pi_t$. Este orden refleja la estructura de una pequeña economía abierta en frecuencia mensual: el tipo de cambio real, se interpreta como una variable principalmente determinada por condiciones externas de competitividad y demanda mundial, por lo que no responde de manera contemporánea a choques domésticos, mientras que la actividad puede reaccionar dentro del mes a cambios en los precios relativos externos, medidos por el tipo de cambio real, sin embargo no ajusta instantáneamente a perturbaciones puramente nominales en el tipo de cambio ni en la inflación. 

A su vez, el tipo de cambio nominal, determinado en mercados financieros relativamente más flexibles, puede responder contemporáneamente a choques reales (del tipo de cambio y de la brecha del producto), y la inflación se sitúa al final de la recursión bajo la hipótesis de rigideces nominales, de modo que los precios al consumidor incorporan con rezago la información contenida en las demás variables. Este esquema es consistente con la literatura de transmisión cambiaria en economías emergentes y con aplicaciones previas para Guatemala.



